name: Valide packer template

on:
  pull_request:
  push:
    branches: [main]
jobs:
  packer_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Install Packer
        run: sudo apt install packer
      - name: Packer validate
        uses: dawitnida/packer-github-actions/validate@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEMPLATE_FILE_NAME: ${{ env.TEMPLATE_FILE_NAME }}