name: Valide packer template

on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  packer_validate:
    runs-on: dawitnida/packer-github-actions:v1.0.1
    steps:
      - name: Packer validate
        uses: dawitnida/packer-github-actions/validate@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEMPLATE_FILE_NAME: ${{ env.TEMPLATE_FILE_NAME }}